final List<Map<String, String>> countryList = [
  {"Country": "Afghanistan", "Curr": "AFN"},
  {"Country": "Albania", "Curr": "ALL"},
  {"Country": "Algeria", "Curr": "DZD"},
  {"Country": "Andorra", "Curr": "EUR"},
  {"Country": "Angola", "Curr": "AOA"},
  {"Country": "Antigua and Barbuda", "Curr": "XCD"},
  {"Country": "Argentina", "Curr": "ARS"},
  {"Country": "Armenia", "Curr": "AMD"},
  {"Country": "Australia", "Curr": "AUD"},
  {"Country": "Austria", "Curr": "EUR"},
  {"Country": "Azerbaijan", "Curr": "AZN"},
  {"Country": "Bahamas", "Curr": "BSD"},
  {"Country": "Bahrain", "Curr": "BHD"},
  {"Country": "Bangladesh", "Curr": "BDT"},
  {"Country": "Barbados", "Curr": "BBD"},
  {"Country": "Belarus", "Curr": "BYN"},
  {"Country": "Belgium", "Curr": "EUR"},
  {"Country": "Belize", "Curr": "BZD"},
  {"Country": "Benin", "Curr": "XOF"},
  {"Country": "Bhutan", "Curr": "BTN"},
  {"Country": "Bolivia", "Curr": "BOB"},
  {"Country": "Bosnia and Herzegovina", "Curr": "BAM"},
  {"Country": "Botswana", "Curr": "BWP"},
  {"Country": "Brazil", "Curr": "BRL"},
  {"Country": "Brunei", "Curr": "BND"},
  {"Country": "Bulgaria", "Curr": "BGN"},
  {"Country": "Burkina Faso", "Curr": "XOF"},
  {"Country": "Burundi", "Curr": "BIF"},
  {"Country": "Cambodia", "Curr": "KHR"},
  {"Country": "Cameroon", "Curr": "XAF"},
  {"Country": "Canada", "Curr": "CAD"},
  {"Country": "Cape Verde", "Curr": "CVE"},
  {"Country": "Central African Republic", "Curr": "XAF"},
  {"Country": "Chad", "Curr": "XAF"},
  {"Country": "Chile", "Curr": "CLP"},
  {"Country": "China", "Curr": "CNY"},
  {"Country": "Colombia", "Curr": "COP"},
  {"Country": "Comoros", "Curr": "KMF"},
  {"Country": "Costa Rica", "Curr": "CRC"},
  {"Country": "Croatia", "Curr": "HRK"},
  {"Country": "Cuba", "Curr": "CUP"},
  {"Country": "Cyprus", "Curr": "EUR"},
  {"Country": "Czech Republic", "Curr": "CZK"},
  {"Country": "Democratic Republic of Congo", "Curr": "CDF"},
  {"Country": "Denmark", "Curr": "DKK"},
  {"Country": "Djibouti", "Curr": "DJF"},
  {"Country": "Dominica", "Curr": "XCD"},
  {"Country": "Dominican Republic", "Curr": "DOP"},
  {"Country": "East Timor", "Curr": "USD"},
  {"Country": "Ecuador", "Curr": "USD"},
  {"Country": "Egypt", "Curr": "EGP"},
  {"Country": "El Salvador", "Curr": "USD"},
  {"Country": "Equatorial Guinea", "Curr": "XAF"},
  {"Country": "Eritrea", "Curr": "ERN"},
  {"Country": "Estonia", "Curr": "EUR"},
  {"Country": "Ethiopia", "Curr": "ETB"},
  {"Country": "Fiji", "Curr": "FJD"},
  {"Country": "Finland", "Curr": "EUR"},
  {"Country": "France", "Curr": "EUR"},
  {"Country": "Gabon", "Curr": "XAF"},
  {"Country": "Gambia", "Curr": "GMD"},
  {"Country": "Georgia", "Curr": "GEL"},
  {"Country": "Germany", "Curr": "EUR"},
  {"Country": "Ghana", "Curr": "GHS"},
  {"Country": "Greece", "Curr": "EUR"},
  {"Country": "Grenada", "Curr": "XCD"},
  {"Country": "Guatemala", "Curr": "GTQ"},
  {"Country": "Guinea", "Curr": "GNF"},
  {"Country": "Guinea-Bissau", "Curr": "XOF"},
  {"Country": "Guyana", "Curr": "GYD"},
  {"Country": "Haiti", "Curr": "HTG"},
  {"Country": "Honduras", "Curr": "HNL"},
  {"Country": "Hungary", "Curr": "HUF"},
  {"Country": "Iceland", "Curr": "ISK"},
  {"Country": "India", "Curr": "INR"},
  {"Country": "Indonesia", "Curr": "IDR"},
  {"Country": "Iran", "Curr": "IRR"},
  {"Country": "Iraq", "Curr": "IQD"},
  {"Country": "Ireland", "Curr": "EUR"},
  {"Country": "Israel", "Curr": "ILS"},
  {"Country": "Italy", "Curr": "EUR"},
  {"Country": "Ivory Coast", "Curr": "XOF"},
  {"Country": "Jamaica", "Curr": "JMD"},
  {"Country": "Japan", "Curr": "JPY"},
  {"Country": "Jordan", "Curr": "JOD"},
  {"Country": "Kazakhstan", "Curr": "KZT"},
  {"Country": "Kenya", "Curr": "KES"},
  {"Country": "Kiribati", "Curr": "AUD"},
  {"Country": "Korea, North", "Curr": "KPW"},
  {"Country": "Korea, South", "Curr": "KRW"},
  {"Country": "Kosovo", "Curr": "EUR"},
  {"Country": "Kuwait", "Curr": "KWD"},
  {"Country": "Kyrgyzstan", "Curr": "KGS"},
  {"Country": "Laos", "Curr": "LAK"},
  {"Country": "Latvia", "Curr": "EUR"},
  {"Country": "Lebanon", "Curr": "LBP"},
  {"Country": "Lesotho", "Curr": "LSL"},
  {"Country": "Liberia", "Curr": "LRD"},
  {"Country": "Libya", "Curr": "LYD"},
  {"Country": "Liechtenstein", "Curr": "CHF"},
  {"Country": "Lithuania", "Curr": "EUR"},
  {"Country": "Luxembourg", "Curr": "EUR"},
  {"Country": "Macedonia", "Curr": "MKD"},
  {"Country": "Madagascar", "Curr": "MGA"},
  {"Country": "Malawi", "Curr": "MWK"},
  {"Country": "Malaysia", "Curr": "MYR"},
  {"Country": "Maldives", "Curr": "MVR"},
  {"Country": "Mali", "Curr": "XOF"},
  {"Country": "Malta", "Curr": "EUR"},
  {"Country": "Marshall Islands", "Curr": "USD"},
  {"Country": "Mauritania", "Curr": "MRO"},
  {"Country": "Mauritius", "Curr": "MUR"},
  {"Country": "Mexico", "Curr": "MXN"},
  {"Country": "Micronesia", "Curr": "USD"},
  {"Country": "Moldova", "Curr": "MDL"},
  {"Country": "Monaco", "Curr": "EUR"},
  {"Country": "Mongolia", "Curr": "MNT"},
  {"Country": "Montenegro", "Curr": "EUR"},
  {"Country": "Morocco", "Curr": "MAD"},
  {"Country": "Mozambique", "Curr": "MZN"},
  {"Country": "Myanmar", "Curr": "MMK"},
  {"Country": "Namibia", "Curr": "NAD"},
  {"Country": "Nauru", "Curr": "AUD"},
  {"Country": "Nepal", "Curr": "NPR"},
  {"Country": "Netherlands", "Curr": "EUR"},
  {"Country": "New Zealand", "Curr": "NZD"},
  {"Country": "Nicaragua", "Curr": "NIO"},
  {"Country": "Niger", "Curr": "XOF"},
  {"Country": "Nigeria", "Curr": "NGN"},
  {"Country": "Norway", "Curr": "NOK"},
  {"Country": "Oman", "Curr": "OMR"},
  {"Country": "Pakistan", "Curr": "PKR"},
  {"Country": "Palau", "Curr": "USD"},
  {"Country": "Palestine", "Curr": "ILS"},
  {"Country": "Panama", "Curr": "PAB"},
  {"Country": "Papua New Guinea", "Curr": "PGK"},
  {"Country": "Paraguay", "Curr": "PYG"},
  {"Country": "Peru", "Curr": "PEN"},
  {"Country": "Philippines", "Curr": "PHP"},
  {"Country": "Poland", "Curr": "PLN"},
  {"Country": "Portugal", "Curr": "EUR"},
  {"Country": "Qatar", "Curr": "QAR"},
  {"Country": "Republic of the Congo", "Curr": "XAF"},
  {"Country": "Romania", "Curr": "RON"},
  {"Country": "Russia", "Curr": "RUB"},
  {"Country": "Rwanda", "Curr": "RWF"},
  {"Country": "Saint Kitts and Nevis", "Curr": "XCD"},
  {"Country": "Saint Lucia", "Curr": "XCD"},
  {"Country": "Saint Vincent and the Grenadines", "Curr": "XCD"},
  {"Country": "Samoa", "Curr": "WST"},
  {"Country": "San Marino", "Curr": "EUR"},
  {"Country": "São Tomé and Príncipe", "Curr": "STD"},
  {"Country": "Saudi Arabia", "Curr": "SAR"},
  {"Country": "Senegal", "Curr": "XOF"},
  {"Country": "Serbia", "Curr": "RSD"},
  {"Country": "Seychelles", "Curr": "SCR"},
  {"Country": "Sierra Leone", "Curr": "SLL"},
  {"Country": "Singapore", "Curr": "SGD"},
  {"Country": "Slovakia", "Curr": "EUR"},
  {"Country": "Slovenia", "Curr": "EUR"},
  {"Country": "Solomon Islands", "Curr": "SBD"},
  {"Country": "Somalia", "Curr": "SOS"},
  {"Country": "South Africa", "Curr": "ZAR"},
  {"Country": "South Sudan", "Curr": "SSP"},
  {"Country": "Spain", "Curr": "EUR"},
  {"Country": "Sri Lanka", "Curr": "LKR"},
  {"Country": "Sudan", "Curr": "SDG"},
  {"Country": "Suriname", "Curr": "SRD"},
  {"Country": "Swaziland", "Curr": "SZL"},
  {"Country": "Sweden", "Curr": "SEK"},
  {"Country": "Switzerland", "Curr": "CHF"},
  {"Country": "Syria", "Curr": "SYP"},
  {"Country": "Taiwan", "Curr": "TWD"},
  {"Country": "Tajikistan", "Curr": "TJS"},
  {"Country": "Tanzania", "Curr": "TZS"},
  {"Country": "Thailand", "Curr": "THB"},
  {"Country": "Togo", "Curr": "XOF"},
  {"Country": "Tonga", "Curr": "TOP"},
  {"Country": "Trinidad and Tobago", "Curr": "TTD"},
  {"Country": "Tunisia", "Curr": "TND"},
  {"Country": "Turkey", "Curr": "TRY"},
  {"Country": "Turkmenistan", "Curr": "TMT"},
  {"Country": "Tuvalu", "Curr": "AUD"},
  {"Country": "Uganda", "Curr": "UGX"},
  {"Country": "Ukraine", "Curr": "UAH"},
  {"Country": "United Arab Emirates", "Curr": "AED"},
  {"Country": "United Kingdom", "Curr": "GBP"},
  {"Country": "United States", "Curr": "USD"},
  {"Country": "Uruguay", "Curr": "UYU"},
  {"Country": "Uzbekistan", "Curr": "UZS"},
  {"Country": "Vanuatu", "Curr": "VUV"},
  {"Country": "Vatican City", "Curr": "EUR"},
  {"Country": "Venezuela", "Curr": "VEF"},
  {"Country": "Vietnam", "Curr": "VND"},
  {"Country": "Yemen", "Curr": "YER"},
  {"Country": "Zambia", "Curr": "ZMW"},
  {"Country": "Zimbabwe", "Curr": "USD"}
];
